### ISSUE TITLE
connect to Mysql timeout.

### ISSUE THREAD

**Issue by macknight** [caryyu/javashop#2]
So how can I connect Mysql installed on CentOS, while JavaShop is in docker container?

**Comment by caryyu** [comment]
`ifconfig` find out what your LAN IP is, typically, it will be something like `192.168.1.x`, let's assume 192.168.1.8 and then the application inside the container can use 192.168.18:3306 to access your mysql

**Comment by caryyu** [comment]
And if you'd like to run your mysql as a docker container, you can use `--link` option of `docker run` to expose its internal dns in your application, for instance, `--link mysql:mysql`, after then, you can directly use like this: `mysql:3306`
